<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lego_mindstorm" nsURI="http://occiware.org/lego_mindstorm/ecore"
    nsPrefix="lego_mindstorm">
  <eClassifiers xsi:type="ecore:EClass" name="Lego_mindstom_ntx2" eSuperTypes="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
    <eOperations name="move_forward">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value="Move forward"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="move_backward">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value="Move backward"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="rotate_right">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value="Rotate right"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="rotate_left">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value="Rotate left"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="stop_move">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value="Stop move"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="move_speed" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mac_address" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robotgator" eSuperTypes="#//Lego_mindstom_ntx2">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
    <eOperations name="open_mouth">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="close_mouth">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="read_ultra_sound">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ultra_sound_value" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
